artifact_uri: file:C:/Users/madha saikumar/PycharmProjects/PythonProject8/notebooks/../mlflow/runs/782831043164091452/4db4b17f1062404f9b15c811d3e9173c/artifacts
end_time: 1773999519990
entry_point_name: ''
experiment_id: '782831043164091452'
lifecycle_stage: active
run_id: 4db4b17f1062404f9b15c811d3e9173c
run_name: XGBoost_Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1773999513818
status: 3
tags: []
user_id: madha saikumar
