artifact_location: file:C:/Users/madha saikumar/PycharmProjects/PythonProject8/notebooks/../mlflow/runs/782831043164091452
creation_time: 1773999513581
experiment_id: '782831043164091452'
last_update_time: 1773999513581
lifecycle_stage: active
name: IPO_Listing_Gain_Prediction
workspace: default
