artifact_uri: file:C:/Users/madha saikumar/PycharmProjects/PythonProject8/notebooks/../mlflow/runs/782831043164091452/bc4cb7bd87044dfd9bf5c54398ac94b0/artifacts
end_time: 1773999576168
entry_point_name: ''
experiment_id: '782831043164091452'
lifecycle_stage: active
run_id: bc4cb7bd87044dfd9bf5c54398ac94b0
run_name: XGBoost_Classifier
source_name: ''
source_type: 4
source_version: ''
start_time: 1773999572023
status: 3
tags: []
user_id: madha saikumar
